---
title: "BRTE_analysis"
output: html_document
---





```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# library
```{r}
library(lme4)
library(tidyverse)
library(ggplot2)
library(dplyr)
library(car)
library(emmeans)
library(lubridate)
library(lavaan)
library(lavaan.survey)
library(lme4)
library(nlme)
library(lmerTest)
library(piecewiseSEM)
library(MuMIn)
library(car)
```


```{r}
rm(list=ls())
```


# source
```{r}
source("/Users/joshuagilman/Documents/code/thesis/stats/thesis_chapter_1/R_files/constants_new.R")
```


example of a split-split plot design model here.
```{r}
# john <- read.table("http://stat.ethz.ch/~meier/teaching/data/john.dat", header = TRUE)
# 
# str(john)
```

# functions
```{r}
stdError <- function(x) {
  sd(x) / sqrt(length(x))
}

normality_visualization <- function(model) {
  hist(resid(model)) #residuals all look OK
  plot(model,3) 
  plot(model,1)
  plot(model,2)
  plot(model,4)
}

# heterogenerity of variance visualizations
boxplot_visualization <- function(dataframe, x_var, y_var) {
  x_var <- enquo(x_var)
  y_var <- enquo(y_var)
  
  dataframe %>%
    ggplot(aes(x = !! x_var, y = !! y_var)) + geom_boxplot() + theme(
    axis.title.x = element_blank(),
    axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 20), size = 12),
    #axis.text.x = element_text(margin = margin(t = 0, r = 10, b = 0, l = 20), size = 12),
    axis.text.x = element_text(vjust = -0.1, size = 12), # cannot figure out how to manually place the facet_strip.
    axis.text = element_text(size = 10),
    strip.placement = "outside",
    #axis.ticks = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_blank(),
    panel.border = element_blank(),
    axis.line = element_line(colour = "black"))
}

model_visualization <- function(model) {
  hist(residuals(model))
  plot(model)
}
```



#.
# BRTE_density
```{r}
#@@@@@@@@@@@@@@@@@@@@@@@@@@@ OUTLIERS @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
dotchart(model_veg$BRTE_density, xlab = "BRTE_density",
         ylab = "Order of the data")

dotchart(model_veg$BRTE_density_sqrt, xlab = "BRTE_density_sqrt",
         ylab = "Order of the data")
```
```{r}
#@@@@@@@@@@@@@@@@@@@@@@@@@ NORMALITY @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
#
lm_BRTE_density <- lm(BRTE_density~precip_treatment*rodent_treatment*burn_treatment,data=model_veg)
normality_visualization(lm_BRTE_density)

lm_BRTE_density_sqrt <- lm(BRTE_density_sqrt~precip_treatment*rodent_treatment*burn_treatment,data=model_veg)
normality_visualization(lm_BRTE_density_sqrt)

lm_BRTE_density_sqrt_sqrt <- lm(BRTE_density_sqrt_sqrt ~ precip_treatment*rodent_treatment*burn_treatment,data=model_veg)
normality_visualization(lm_BRTE_density_sqrt)
```


```{r}
boxplot_visualization(model_veg, block, BRTE_density) 
# slightly unequal

boxplot_visualization(model_veg, year, BRTE_density) 
# slightly unequal

boxplot_visualization(model_veg, precip_treatment, BRTE_density) 
# slightly unequal

boxplot_visualization(model_veg, rodent_treatment, BRTE_density) 
# slightly unequal

boxplot_visualization(model_veg, burn_treatment, BRTE_density)  
```


# @model
```{r}
BRTE_density_model = lmer(BRTE_density ~ precip_treatment * rodent_treatment * burn_treatment * year + (1|whole_plot) + (1|split_plot) + (1|block), data = model_veg)
model_visualization(BRTE_density_model)

BRTE_density_sqrt_model = lmer(BRTE_density_sqrt ~ precip_treatment * rodent_treatment * burn_treatment * year + (1|whole_plot) + (1|split_plot) + (1|block), data = model_veg)
model_visualization(BRTE_density_sqrt_model)

BRTE_density_sqrt_sqrt_model = lmer(BRTE_density_sqrt_sqrt ~ precip_treatment * rodent_treatment * burn_treatment * year + (1|whole_plot) + (1|split_plot) + (1|block), data = model_veg)
model_visualization(BRTE_density_sqrt_sqrt_model)
```
7.8e-6# @winner
```{r}
anova(BRTE_density_model)
# anova(BRTE_density_sqrt_model)
# anova(BRTE_density_sqrt_sqrt_model)
```

# @ave BRTE_averages
```{r}
# model_veg %>%
#   #filter(year != 2020) %>%
#   dplyr::group_by(rodent_treatment, burn_treatment) %>%
#   dplyr::summarise(mean = mean(BRTE_density), standard_error = stdError(BRTE_density)) %>%
#   View()
```

# @plots
```{r}
facet_panel_labels_rodent <- list('rodent_control' = "Rodent-access", 'rodent_exclusion' = "Rodent-exclusion")

plot_labeller <- function(variable, value) {
  return(facet_panel_labels_rodent[value])
}
```


```{r}

model_veg %>%
  filter(block != 1 & block != 4) %>% 
  filter(year == 2018) %>% 
  filter(precip_treatment != "control") %>% 
  dplyr::group_by(rodent_treatment, burn_treatment, precip_treatment, year) %>%
  dplyr::summarise(mean = mean(BRTE_density), standard_error = stdError(BRTE_density)) %>% 
  ggplot(aes(x = burn_treatment, y = mean, fill = precip_treatment)) + geom_bar(stat = "identity", width = 0.90, position = position_dodge(width = 0.90)) + geom_errorbar(aes(ymin = mean - standard_error, ymax = mean + standard_error, width = 0.1), position = position_dodge(width = 0.90), stat = "identity") + scale_x_discrete(labels = c("burn" = "Burn", "re_burn" = "Reburn")) + facet_wrap(. ~ rodent_treatment, labeller = plot_labeller, strip.position = "bottom") + scale_fill_manual(labels = c("Drought", "Drought-pulse"), values = c("grey80", "grey20")) + ylab(expression(paste(italic("Bromus tectorum") ~ "(m" ^ "-2" ~ ")"))) + theme(
    axis.title.x = element_blank(),
    axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 20), size = 12),
    #axis.text.x = element_text(margin = margin(t = 0, r = 10, b = 0, l = 20), size = 12),
    axis.text.x = element_text(vjust = -0.1, size = 12), # cannot figure out how to manually place the facet_strip.
    axis.text = element_text(size = 10),
    strip.placement = "outside",
    #axis.ticks = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_blank(),
    panel.border = element_blank(),
    axis.line = element_line(colour = "black"),
    legend.position = c(0.25, 0.8),
    legend.title = element_blank()
    ) 

model_veg %>%
  filter(block != 1 & block != 4) %>% 
  filter(year == 2019) %>% 
  filter(precip_treatment != "control") %>% 
  dplyr::group_by(rodent_treatment, burn_treatment, precip_treatment, year) %>%
  dplyr::summarise(mean = mean(BRTE_density), standard_error = stdError(BRTE_density)) %>% 
  ggplot(aes(x = burn_treatment, y = mean, fill = precip_treatment)) + geom_bar(stat = "identity", width = 0.90, position = position_dodge(width = 0.90)) + geom_errorbar(aes(ymin = mean - standard_error, ymax = mean + standard_error, width = 0.1), position = position_dodge(width = 0.90), stat = "identity") + scale_x_discrete(labels = c("burn" = "Burn", "re_burn" = "Reburn")) + facet_wrap(. ~ rodent_treatment, labeller = plot_labeller, strip.position = "bottom") + scale_fill_manual(labels = c("Drought", "Drought-pulse"), values = c("grey80", "grey20")) + ylab(expression(paste(italic("Bromus tectorum") ~ "(m" ^ "-2" ~ ")"))) + theme(
    axis.title.x = element_blank(),
    axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 20), size = 12),
    #axis.text.x = element_text(margin = margin(t = 0, r = 10, b = 0, l = 20), size = 12),
    axis.text.x = element_text(vjust = -0.1, size = 12), # cannot figure out how to manually place the facet_strip.
    axis.text = element_text(size = 10),
    strip.placement = "outside",
    #axis.ticks = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_blank(),
    panel.border = element_blank(),
    axis.line = element_line(colour = "black"),
    legend.position = c(0.25, 0.8),
    legend.title = element_blank()
    ) 

model_veg %>%
  filter(block != 1 & block != 4) %>% 
  filter(year == 2020) %>% 
  filter(precip_treatment != "control") %>% 
  dplyr::group_by(rodent_treatment, burn_treatment, precip_treatment, year) %>%
  dplyr::summarise(mean = mean(BRTE_density), standard_error = stdError(BRTE_density)) %>% 
  ggplot(aes(x = burn_treatment, y = mean, fill = precip_treatment)) + geom_bar(stat = "identity", width = 0.90, position = position_dodge(width = 0.90)) + geom_errorbar(aes(ymin = mean - standard_error, ymax = mean + standard_error, width = 0.1), position = position_dodge(width = 0.90), stat = "identity") + scale_x_discrete(labels = c("burn" = "Burn", "re_burn" = "Reburn")) + facet_wrap(. ~ rodent_treatment, labeller = plot_labeller, strip.position = "bottom") + scale_fill_manual(labels = c("Drought", "Drought-pulse"), values = c("grey80", "grey20")) + ylab(expression(paste(italic("Bromus tectorum") ~ "(m" ^ "-2" ~ ")"))) + theme(
    axis.title.x = element_blank(),
    axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 20), size = 12),
    #axis.text.x = element_text(margin = margin(t = 0, r = 10, b = 0, l = 20), size = 12),
    axis.text.x = element_text(vjust = -0.1, size = 12), # cannot figure out how to manually place the facet_strip.
    axis.text = element_text(size = 10),
    strip.placement = "outside",
    #axis.ticks = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_blank(),
    panel.border = element_blank(),
    axis.line = element_line(colour = "black"),
    legend.position = c(0.25, 0.8),
    legend.title = element_blank()
    ) 



```

```{r}
# ggsave(path = tc1_photo_path, "STORY_BRTE_density_3_way.png", width = 6, height = 3.5)

model_veg %>%
  filter(block != 1 & block != 4) %>% 
  filter(precip_treatment != "control") %>% 
  dplyr::group_by(rodent_treatment,precip_treatment) %>%
  dplyr::summarise(mean = mean(BRTE_density), standard_error = stdError(BRTE_density)) %>% 
  ggplot(aes(x = rodent_treatment, y = mean, fill = precip_treatment)) + geom_bar(stat = "identity", width = 0.90, position = position_dodge(width = 0.90)) + geom_errorbar(aes(ymin = mean - standard_error, ymax = mean + standard_error, width = 0.1), position = position_dodge(width = 0.90), stat = "identity") + scale_fill_manual(labels = c("Drought", "Drought-pulse"), values = c("grey80", "grey20")) + ylab(expression(paste(italic("B. tectorum") ~ "(m" ^ "-2" ~ ")"))) + scale_y_continuous(limits = c(0,2000)) + theme(
    axis.title.x = element_blank(),
    axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 20), size = 12),
    #axis.text.x = element_text(margin = margin(t = 0, r = 10, b = 0, l = 20), size = 12),
    axis.text.x = element_text(vjust = -0.1, size = 12), # cannot figure out how to manually place the facet_strip.
    axis.text = element_text(size = 10),
    strip.placement = "outside",
    #axis.ticks = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_blank(),
    panel.border = element_blank(),
    axis.line = element_line(colour = "black"),
    legend.position = c(0.25, 0.8),
    legend.title = element_blank()
    )

model_veg %>%
  filter(block != 1 & block != 4) %>% 
  filter(precip_treatment != "control") %>% 
  dplyr::group_by(rodent_treatment,burn_treatment) %>%
  dplyr::summarise(mean = mean(BRTE_density), standard_error = stdError(BRTE_density)) %>% 
  ggplot(aes(x = rodent_treatment, y = mean, fill = burn_treatment)) + geom_bar(stat = "identity", width = 0.90, position = position_dodge(width = 0.90)) + geom_errorbar(aes(ymin = mean - standard_error, ymax = mean + standard_error, width = 0.1), position = position_dodge(width = 0.90), stat = "identity") + scale_fill_manual(labels = c("Burn", "Reburn"), values = c("grey80", "grey20")) + ylab(expression(paste(italic("B. tectorum") ~ "(m" ^ "-2" ~ ")"))) + scale_y_continuous(limits = c(0,2000)) + theme(
    axis.title.x = element_blank(),
    axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 20), size = 12),
    #axis.text.x = element_text(margin = margin(t = 0, r = 10, b = 0, l = 20), size = 12),
    axis.text.x = element_text(vjust = -0.1, size = 12), # cannot figure out how to manually place the facet_strip.
    axis.text = element_text(size = 10),
    strip.placement = "outside",
    #axis.ticks = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_blank(),
    panel.border = element_blank(),
    axis.line = element_line(colour = "black"),
    legend.position = c(0.25, 0.8),
    legend.title = element_blank()
    )

```

#.
# BRTE_canopy_cover
```{r}
#@@@@@@@@@@@@@@@@@@@@@@@@@@@ OUTLIERS @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
dotchart(model_veg$BRTE_canopy_cover, xlab = "BRTE_canopy_cover",
         ylab = "Order of the data")

dotchart(model_veg$BRTE_canopy_cover_sqrt, xlab = "BRTE_canopy_cover_sqrt",
         ylab = "Order of the data")
```
```{r}
#@@@@@@@@@@@@@@@@@@@@@@@@@ NORMALITY @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
#
lm_BRTE_canopy_cover <- lm(BRTE_canopy_cover~precip_treatment*rodent_treatment*burn_treatment,data=model_veg)
normality_visualization(lm_BRTE_canopy_cover)

lm_BRTE_canopy_cover_sqrt <- lm(BRTE_canopy_cover_sqrt~precip_treatment*rodent_treatment*burn_treatment,data=model_veg)
normality_visualization(lm_BRTE_canopy_cover_sqrt)
```


```{r}
boxplot_visualization(model_veg, block, BRTE_canopy_cover) 
# slightly unequal

boxplot_visualization(model_veg, year, BRTE_canopy_cover) 
# slightly unequal

boxplot_visualization(model_veg, precip_treatment, BRTE_canopy_cover) 
# slightly unequal

boxplot_visualization(model_veg, rodent_treatment, BRTE_canopy_cover) 
# slightly unequal

boxplot_visualization(model_veg, burn_treatment, BRTE_canopy_cover)  
```


# @model
```{r}
BRTE_canopy_cover_model = lmer(BRTE_canopy_cover ~ precip_treatment * rodent_treatment * burn_treatment * year + (1|whole_plot) + (1|split_plot) + (1|block), data = model_veg)
model_visualization(BRTE_canopy_cover_model)

# BRTE_canopy_cover_sqrt_model = lmer(BRTE_canopy_cover_sqrt ~ precip_treatment * rodent_treatment * burn_treatment * year + (1|whole_plot) + (1|split_plot) + (1|block), data = model_veg)
# model_visualization(BRTE_canopy_cover_sqrt_model)

```

# @winner
```{r}
anova(BRTE_canopy_cover_model)
#anova(BRTE_canopy_cover_sqrt_model)
```

# @ave BRTE_averages
```{r}
# model_veg %>%
#   #filter(year != 2018) %>%
#   dplyr::group_by(burn_treatment) %>%
#   dplyr::summarise(mean = mean(BRTE_canopy_cover), standard_error = stdError(BRTE_canopy_cover)) %>%
#   View()
```

# @plots
```{r}
facet_panel_labels_rodent <- list('rodent_control' = "Rodent-access", 'rodent_exclusion' = "Rodent-exclusion")

plot_labeller <- function(variable, value) {
  return(facet_panel_labels_rodent[value])
}
```


```{r}

model_veg %>%
  filter(block != 1 & block != 4) %>% 
  filter(precip_treatment != "control") %>% 
  dplyr::group_by(rodent_treatment, burn_treatment, precip_treatment) %>%
  dplyr::summarise(mean = mean(BRTE_canopy_cover), standard_error = stdError(BRTE_canopy_cover)) %>% 
  ggplot(aes(x = burn_treatment, y = mean, fill = precip_treatment)) + geom_bar(stat = "identity", width = 0.90, position = position_dodge(width = 0.90)) + geom_errorbar(aes(ymin = mean - standard_error, ymax = mean + standard_error, width = 0.1), position = position_dodge(width = 0.90), stat = "identity") + scale_x_discrete(labels = c("burn" = "Burn", "re_burn" = "Reburn")) + facet_wrap(. ~ rodent_treatment, labeller = plot_labeller, strip.position = "bottom") + scale_fill_manual(labels = c("Drought", "Drought-pulse"), values = c("grey80", "grey20")) + ylab(expression(paste(italic("Bromus tectorum") ~ "(% cover)"))) + theme(
    axis.title.x = element_blank(),
    axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 20), size = 12),
    #axis.text.x = element_text(margin = margin(t = 0, r = 10, b = 0, l = 20), size = 12),
    axis.text.x = element_text(vjust = -0.1, size = 12), # cannot figure out how to manually place the facet_strip.
    axis.text = element_text(size = 10),
    strip.placement = "outside",
    #axis.ticks = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_blank(),
    panel.border = element_blank(),
    axis.line = element_line(colour = "black"),
    legend.position = c(0.25, 0.8),
    legend.title = element_blank()
    ) 
ggsave(path = tc1_photo_path, "STORY_BRTE_cover_3_way.png", width = 6, height = 3.5)


model_veg %>%
  filter(block != 1 & block != 4) %>% 
  filter(precip_treatment != "control") %>% 
  dplyr::group_by(rodent_treatment,precip_treatment) %>%
  dplyr::summarise(mean = mean(BRTE_canopy_cover), standard_error = stdError(BRTE_canopy_cover)) %>% 
  ggplot(aes(x = rodent_treatment, y = mean, fill = precip_treatment)) + geom_bar(stat = "identity", width = 0.90, position = position_dodge(width = 0.90)) + geom_errorbar(aes(ymin = mean - standard_error, ymax = mean + standard_error, width = 0.1), position = position_dodge(width = 0.90), stat = "identity") + scale_fill_manual(labels = c("Drought", "Drought-pulse"), values = c("grey80", "grey20")) + ylab(expression(paste(italic("Bromus tectorum") ~ "(% cover)"))) + scale_y_continuous(limits = c(0,1)) + theme(
    axis.title.x = element_blank(),
    axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 20), size = 12),
    #axis.text.x = element_text(margin = margin(t = 0, r = 10, b = 0, l = 20), size = 12),
    axis.text.x = element_text(vjust = -0.1, size = 12), # cannot figure out how to manually place the facet_strip.
    axis.text = element_text(size = 10),
    strip.placement = "outside",
    #axis.ticks = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_blank(),
    panel.border = element_blank(),
    axis.line = element_line(colour = "black"),
    legend.position = c(0.25, 0.8),
    legend.title = element_blank()
    ) 


```
