---
title: "CETE_analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# library
```{r}
library(lme4)
library(tidyverse)
library(ggplot2)
library(dplyr)
library(car)
library(emmeans)
library(lubridate)
library(lavaan)
library(lavaan.survey)
library(lme4)
library(nlme)
library(lmerTest)
library(piecewiseSEM)
library(MuMIn)
library(car)
```


```{r}
rm(list=ls())
```


# source
```{r}
source("/Users/joshuagilman/Documents/code/thesis/stats/thesis_chapter_1/R_files/constants_new.R")
```


# functions
```{r}
stdError <- function(x) {
  sd(x) / sqrt(length(x))
}

normality_visualization <- function(model) {
  hist(resid(model)) #residuals all look OK
  plot(model,3) 
  plot(model,1)
  plot(model,2)
  plot(model,4)
}

# heterogenerity of variance visualizations
boxplot_visualization <- function(dataframe, x_var, y_var) {
  x_var <- enquo(x_var)
  y_var <- enquo(y_var)
  
  dataframe %>%
    ggplot(aes(x = !! x_var, y = !! y_var)) + geom_boxplot() + theme(
    axis.title.x = element_blank(),
    axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 20), size = 12),
    #axis.text.x = element_text(margin = margin(t = 0, r = 10, b = 0, l = 20), size = 12),
    axis.text.x = element_text(vjust = -0.1, size = 12), # cannot figure out how to manually place the facet_strip.
    axis.text = element_text(size = 10),
    strip.placement = "outside",
    #axis.ticks = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_blank(),
    panel.border = element_blank(),
    axis.line = element_line(colour = "black"))
}

model_visualization <- function(model) {
  hist(residuals(model))
  plot(model)
}
```


#.
# CETE_density
```{r}
#@@@@@@@@@@@@@@@@@@@@@@@@@@@ OUTLIERS @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
dotchart(model_veg$CETE_density, xlab = "CETE_density",
         ylab = "Order of the data")

dotchart(model_veg$CETE_density_sqrt, xlab = "CETE_density_sqrt",
         ylab = "Order of the data")
```


```{r}
#@@@@@@@@@@@@@@@@@@@@@@@@@ NORMALITY @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
#
lm_CETE_density<- lm(CETE_density~precip_treatment*rodent_treatment*burn_treatment,data=model_veg)
normality_visualization(lm_CETE_density)

lm_CETE_density_sqrt<- lm(CETE_density_sqrt~precip_treatment*rodent_treatment*burn_treatment,data=model_veg)
normality_visualization(lm_CETE_density_sqrt)
```


```{r}
boxplot_visualization(model_veg, block, CETE_density) 
# slightly unequal

boxplot_visualization(model_veg, year, CETE_density) 
# slightly unequal

boxplot_visualization(model_veg, precip_treatment, CETE_density) 
# slightly unequal

boxplot_visualization(model_veg, rodent_treatment, CETE_density) 
# slightly unequal

boxplot_visualization(model_veg, burn_treatment, CETE_density)  
```


# @model
```{r}
CETE_density_model = lmer(CETE_density ~ precip_treatment * rodent_treatment * burn_treatment * year + (1|whole_plot) + (1|split_plot) + (1|block), data = model_veg)
model_visualization(CETE_density_model)

CETE_density_sqrt_model = lmer(CETE_density_sqrt ~ precip_treatment * rodent_treatment * burn_treatment * year + (1|whole_plot) + (1|split_plot) + (1|block), data = model_veg)
model_visualization(CETE_density_sqrt_model)
```
# @winner
```{r}
#anova(CETE_density_model)
anova(CETE_density_sqrt_model)
```

# @ave CETE_averages
```{r}
# model_veg %>%
#   #filter(year != 2020) %>%
#   dplyr::group_by(burn_treatment) %>%
#   dplyr::summarise(mean = mean(CETE_density), standard_error = stdError(CETE_density)) %>%
#   View()
```

# @plots
```{r}
facet_panel_labels_rodent <- list('rodent_control' = "Rodent-access", 'rodent_exclusion' = "Rodent-exclusion")

plot_labeller <- function(variable, value) {
  return(facet_panel_labels_rodent[value])
}
```


```{r}

model_veg %>%
  filter(block != 1 & block != 4) %>% 
  filter(year == 2018) %>% 
  filter(precip_treatment != "control") %>% 
  dplyr::group_by(rodent_treatment, burn_treatment, precip_treatment, year) %>%
  dplyr::summarise(mean = mean(CETE_density), standard_error = stdError(CETE_density)) %>% 
  ggplot(aes(x = burn_treatment, y = mean, fill = precip_treatment)) + geom_bar(stat = "identity", width = 0.90, position = position_dodge(width = 0.90)) + geom_errorbar(aes(ymin = mean - standard_error, ymax = mean + standard_error, width = 0.1), position = position_dodge(width = 0.90), stat = "identity") + scale_x_discrete(labels = c("burn" = "Burn", "re_burn" = "Reburn")) + facet_wrap(. ~ rodent_treatment, labeller = plot_labeller, strip.position = "bottom") + scale_fill_manual(labels = c("Drought", "Drought-pulse"), values = c("grey80", "grey20")) + ylab(expression(paste(italic("CETE") ~ "(m" ^ "-2" ~ ")"))) + theme(
    axis.title.x = element_blank(),
    axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 20), size = 12),
    #axis.text.x = element_text(margin = margin(t = 0, r = 10, b = 0, l = 20), size = 12),
    axis.text.x = element_text(vjust = -0.1, size = 12), # cannot figure out how to manually place the facet_strip.
    axis.text = element_text(size = 10),
    strip.placement = "outside",
    #axis.ticks = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_blank(),
    panel.border = element_blank(),
    axis.line = element_line(colour = "black"),
    legend.position = c(0.25, 0.8),
    legend.title = element_blank()
    ) 

model_veg %>%
  filter(block != 1 & block != 4) %>% 
  filter(year == 2019) %>% 
  filter(precip_treatment != "control") %>% 
  dplyr::group_by(rodent_treatment, burn_treatment, precip_treatment, year) %>%
  dplyr::summarise(mean = mean(CETE_density), standard_error = stdError(CETE_density)) %>% 
  ggplot(aes(x = burn_treatment, y = mean, fill = precip_treatment)) + geom_bar(stat = "identity", width = 0.90, position = position_dodge(width = 0.90)) + geom_errorbar(aes(ymin = mean - standard_error, ymax = mean + standard_error, width = 0.1), position = position_dodge(width = 0.90), stat = "identity") + scale_x_discrete(labels = c("burn" = "Burn", "re_burn" = "Reburn")) + facet_wrap(. ~ rodent_treatment, labeller = plot_labeller, strip.position = "bottom") + scale_fill_manual(labels = c("Drought", "Drought-pulse"), values = c("grey80", "grey20")) + ylab(expression(paste(italic("CETE") ~ "(m" ^ "-2" ~ ")"))) + theme(
    axis.title.x = element_blank(),
    axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 20), size = 12),
    #axis.text.x = element_text(margin = margin(t = 0, r = 10, b = 0, l = 20), size = 12),
    axis.text.x = element_text(vjust = -0.1, size = 12), # cannot figure out how to manually place the facet_strip.
    axis.text = element_text(size = 10),
    strip.placement = "outside",
    #axis.ticks = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_blank(),
    panel.border = element_blank(),
    axis.line = element_line(colour = "black"),
    legend.position = c(0.25, 0.8),
    legend.title = element_blank()
    ) 

model_veg %>%
  filter(block != 1 & block != 4) %>% 
  filter(year == 2020) %>% 
  filter(precip_treatment != "control") %>% 
  dplyr::group_by(rodent_treatment, burn_treatment, precip_treatment, year) %>%
  dplyr::summarise(mean = mean(CETE_density), standard_error = stdError(CETE_density)) %>% 
  ggplot(aes(x = burn_treatment, y = mean, fill = precip_treatment)) + geom_bar(stat = "identity", width = 0.90, position = position_dodge(width = 0.90)) + geom_errorbar(aes(ymin = mean - standard_error, ymax = mean + standard_error, width = 0.1), position = position_dodge(width = 0.90), stat = "identity") + scale_x_discrete(labels = c("burn" = "Burn", "re_burn" = "Reburn")) + facet_wrap(. ~ rodent_treatment, labeller = plot_labeller, strip.position = "bottom") + scale_fill_manual(labels = c("Drought", "Drought-pulse"), values = c("grey80", "grey20")) + ylab(expression(paste(italic("CETE") ~ "(m" ^ "-2" ~ ")"))) + theme(
    axis.title.x = element_blank(),
    axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 20), size = 12),
    #axis.text.x = element_text(margin = margin(t = 0, r = 10, b = 0, l = 20), size = 12),
    axis.text.x = element_text(vjust = -0.1, size = 12), # cannot figure out how to manually place the facet_strip.
    axis.text = element_text(size = 10),
    strip.placement = "outside",
    #axis.ticks = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_blank(),
    panel.border = element_blank(),
    axis.line = element_line(colour = "black"),
    legend.position = c(0.25, 0.8),
    legend.title = element_blank()
    ) 



```

```{r}



model_veg %>%
  filter(block != 1 & block != 4) %>% 
  filter(precip_treatment != "control") %>% 
  dplyr::group_by(rodent_treatment,precip_treatment) %>%
  dplyr::summarise(mean = mean(CETE_density), standard_error = stdError(CETE_density)) %>% 
  ggplot(aes(x = rodent_treatment, y = mean, fill = precip_treatment)) + geom_bar(stat = "identity", width = 0.90, position = position_dodge(width = 0.90)) + geom_errorbar(aes(ymin = mean - standard_error, ymax = mean + standard_error, width = 0.1), position = position_dodge(width = 0.90), stat = "identity") + scale_fill_manual(labels = c("Drought", "Drought-pulse"), values = c("grey80", "grey20")) + ylab(expression(paste(italic("C. testiculata") ~ "(m" ^ "-2" ~ ")"))) + scale_y_continuous(limits = c(0,1000)) + theme(
    axis.title.x = element_blank(),
    axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 20), size = 12),
    #axis.text.x = element_text(margin = margin(t = 0, r = 10, b = 0, l = 20), size = 12),
    axis.text.x = element_text(vjust = -0.1, size = 12), # cannot figure out how to manually place the facet_strip.
    axis.text = element_text(size = 10),
    strip.placement = "outside",
    #axis.ticks = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_blank(),
    panel.border = element_blank(),
    axis.line = element_line(colour = "black"),
    legend.position = c(0.25, 0.8),
    legend.title = element_blank()
    ) 

ggsave(path = tc1_photo_path, "STORY_CETE_precip_rodent.png", width = 6, height = 3.5)


model_veg %>%
  filter(block != 1 & block != 4) %>% 
  filter(precip_treatment != "control") %>% 
  dplyr::group_by(precip_treatment) %>%
  dplyr::summarise(mean = mean(CETE_density), standard_error = stdError(CETE_density)) %>% 
  ggplot(aes(x = precip_treatment, y = mean, fill = precip_treatment)) + geom_bar(stat = "identity", width = 0.90, position = position_dodge(width = 0.90)) + geom_errorbar(aes(ymin = mean - standard_error, ymax = mean + standard_error, width = 0.1), position = position_dodge(width = 0.90), stat = "identity") + scale_fill_manual(labels = c("Drought", "Drought-pulse"), values = c("grey80", "grey20")) + scale_y_continuous(limits = c(0,1000)) + ylab(expression(paste(italic("C. testiculata") ~ "(m" ^ "-2" ~ ")"))) + theme(
    axis.title.x = element_blank(),
    axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 20), size = 12),
    #axis.text.x = element_text(margin = margin(t = 0, r = 10, b = 0, l = 20), size = 12),
    axis.text.x = element_text(vjust = -0.1, size = 12), # cannot figure out how to manually place the facet_strip.
    axis.text = element_text(size = 10),
    strip.placement = "outside",
    #axis.ticks = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_blank(),
    panel.border = element_blank(),
    axis.line = element_line(colour = "black"),
    legend.position = c(0.25, 0.8),
    legend.title = element_blank()
    ) 

ggsave(path = tc1_photo_path, "STORY_CETE_precip.png", width = 6, height = 3.5)


model_veg %>%
  filter(block != 1 & block != 4) %>% 
  filter(rodent_treatment != "control") %>% 
  dplyr::group_by(rodent_treatment, year) %>%
  dplyr::summarise(mean = mean(CETE_density), standard_error = stdError(CETE_density)) %>% 
  ggplot(aes(x = rodent_treatment, y = mean, fill = rodent_treatment)) + geom_bar(stat = "identity", width = 0.90, position = position_dodge(width = 0.90)) + geom_errorbar(aes(ymin = mean - standard_error, ymax = mean + standard_error, width = 0.1), position = position_dodge(width = 0.90), stat = "identity") + scale_fill_manual(labels = c("rodent_control", "rodent-exclusion"), values = c("grey80", "grey20")) + facet_grid(~year) + ylab(expression(paste(italic("C. testiculata") ~ "(m" ^ "-2" ~ ")"))) + theme(
    axis.title.x = element_blank(),
    axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 20), size = 12),
    #axis.text.x = element_text(margin = margin(t = 0, r = 10, b = 0, l = 20), size = 12),
    axis.text.x = element_text(vjust = -0.1, size = 6), # cannot figure out how to manually place the facet_strip.
    axis.text = element_text(size = 10),
    strip.placement = "outside",
    #axis.ticks = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_blank(),
    panel.border = element_blank(),
    axis.line = element_line(colour = "black"),
    legend.position = c(0.20, 0.8),
    legend.title = element_blank()
    ) 

ggsave(path = tc1_photo_path, "STORY_CETE_rodent_year.png", width = 6, height = 3.5)

```
```{r}
model_veg %>%
  filter(block != 1 & block != 4) %>% 
  filter(precip_treatment != "control") %>% 
  dplyr::group_by(rodent_treatment, burn_treatment, precip_treatment) %>%
  dplyr::summarise(mean = mean(CETE_density), standard_error = stdError(CETE_density)) %>% 
  ggplot(aes(x = burn_treatment, y = mean, fill = precip_treatment)) + geom_bar(stat = "identity", width = 0.90, position = position_dodge(width = 0.90)) + geom_errorbar(aes(ymin = mean - standard_error, ymax = mean + standard_error, width = 0.1), position = position_dodge(width = 0.90), stat = "identity") + scale_x_discrete(labels = c("burn" = "Burn", "re_burn" = "Reburn")) + facet_wrap(. ~ rodent_treatment, labeller = plot_labeller, strip.position = "bottom") + scale_fill_manual(labels = c("Drought", "Drought-pulse"), values = c("grey80", "grey20")) + ylab(expression(paste(italic("C. testiculata") ~ "(m" ^ "-2" ~ ")"))) + scale_y_continuous(limits = c(0,1000)) + theme(
    axis.title.x = element_blank(),
    axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 20), size = 12),
    #axis.text.x = element_text(margin = margin(t = 0, r = 10, b = 0, l = 20), size = 12),
    axis.text.x = element_text(vjust = -0.1, size = 12), # cannot figure out how to manually place the facet_strip.
    axis.text = element_text(size = 10),
    strip.placement = "outside",
    #axis.ticks = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_blank(),
    panel.border = element_blank(),
    axis.line = element_line(colour = "black"),
    legend.position = c(0.25, 0.8),
    legend.title = element_blank()
    ) 

ggsave(path = tc1_photo_path, "STORY_CETE_density_3_way.png", width = 6, height = 3.5)
```



# @plot 3-way 
```{r}
model_veg %>%
  filter(block != 1 & block != 4) %>% 
  filter(burn_treatment != "burn") %>% 
  dplyr::group_by(rodent_treatment, precip_treatment) %>%
  dplyr::summarise(mean = mean(CETE_density), standard_error = stdError(CETE_density)) %>% 
  ggplot(aes(x = rodent_treatment, y = mean, group = precip_treatment)) + geom_line(aes(linetype = precip_treatment)) + geom_point() + ylab("pF value") + scale_x_discrete(labels = c("rodent_control" = "rodent-access", "rodent_exclusion" = "rodent-exclusion")) + theme(
      legend.position = c(0.85, 0.85),
      legend.title = element_blank(),
      legend.background = element_blank(),
      legend.key = element_blank(),
      legend.text = element_text(size = 10),
      axis.title.x = element_blank(),
      axis.title.y = element_text(margin = margin(t = 0, r = 15, b = 0, l = 20), size = 10),
      #axis.text.x = element_text(margin = margin(t = 0, r = 10, b = 0, l = 20), size = 12),
      axis.text.x = element_text(vjust = -0.1, size = 12),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      panel.background = element_blank(),
      panel.border = element_blank(),
      axis.line = element_line(colour = "black"))

model_veg %>%
  filter(block != 1 & block != 4) %>% 
  filter(burn_treatment != "reburn") %>% 
  dplyr::group_by(rodent_treatment, precip_treatment) %>%
  dplyr::summarise(mean = mean(CETE_density), standard_error = stdError(CETE_density)) %>% 
  ggplot(aes(x = rodent_treatment, y = mean, group = precip_treatment)) + geom_line(aes(linetype = precip_treatment)) + geom_point() + ylab("pF value") + scale_x_discrete(labels = c("rodent_control" = "rodent-access", "rodent_exclusion" = "rodent-exclusion")) + theme(
      legend.position = c(0.85, 0.85),
      legend.title = element_blank(),
      legend.background = element_blank(),
      legend.key = element_blank(),
      legend.text = element_text(size = 10),
      axis.title.x = element_blank(),
      axis.title.y = element_text(margin = margin(t = 0, r = 15, b = 0, l = 20), size = 10),
      #axis.text.x = element_text(margin = margin(t = 0, r = 10, b = 0, l = 20), size = 12),
      axis.text.x = element_text(vjust = -0.1, size = 12),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      panel.background = element_blank(),
      panel.border = element_blank(),
      axis.line = element_line(colour = "black"))

model_veg %>%
  filter(block != 1 & block != 4) %>% 
  filter(rodent_treatment == "rodent_exclusion") %>% 
  dplyr::group_by(precip_treatment, burn_treatment) %>%
  dplyr::summarise(mean = mean(CETE_density), standard_error = stdError(CETE_density)) %>% 
  ggplot(aes(x = precip_treatment, y = mean, group = burn_treatment)) + geom_line(aes(linetype = burn_treatment)) + geom_point() + ylab("pF value") + theme(
      legend.position = c(0.85, 0.85),
      legend.title = element_blank(),
      legend.background = element_blank(),
      legend.key = element_blank(),
      legend.text = element_text(size = 10),
      axis.title.x = element_blank(),
      axis.title.y = element_text(margin = margin(t = 0, r = 15, b = 0, l = 20), size = 10),
      #axis.text.x = element_text(margin = margin(t = 0, r = 10, b = 0, l = 20), size = 12),
      axis.text.x = element_text(vjust = -0.1, size = 12),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      panel.background = element_blank(),
      panel.border = element_blank(),
      axis.line = element_line(colour = "black"))

model_veg %>%
  filter(block != 1 & block != 4) %>% 
  filter(rodent_treatment == "rodent_control") %>% 
  dplyr::group_by(precip_treatment, burn_treatment) %>%
  dplyr::summarise(mean = mean(CETE_density), standard_error = stdError(CETE_density)) %>% 
  ggplot(aes(x = precip_treatment, y = mean, group = burn_treatment)) + geom_line(aes(linetype = burn_treatment)) + geom_point() + ylab("pF value") + theme(
      legend.position = c(0.85, 0.85),
      legend.title = element_blank(),
      legend.background = element_blank(),
      legend.key = element_blank(),
      legend.text = element_text(size = 10),
      axis.title.x = element_blank(),
      axis.title.y = element_text(margin = margin(t = 0, r = 15, b = 0, l = 20), size = 10),
      #axis.text.x = element_text(margin = margin(t = 0, r = 10, b = 0, l = 20), size = 12),
      axis.text.x = element_text(vjust = -0.1, size = 12),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      panel.background = element_blank(),
      panel.border = element_blank(),
      axis.line = element_line(colour = "black"))
```


